### ISSUE TITLE
Update axios dependecy

### ISSUE THREAD

**Issue by atanaxum** [valeriangalliat/spotify-to-youtube#3]
Hi!

First of all - thanks for your package! Combined with ytdl I'm able to listen spotify's playlists with my bot ^^ But could you update your version of axios?

Thx again! Ciao :)

**Comment by exiify** [comment]
@atanaxum you should probably make the issue here https://github.com/valeriangalliat/youtube-music-api

**Comment by valeriangalliat** [comment]
I just noticed that https://github.com/emresenyuva/youtube-music-api merged my PR https://github.com/emresenyuva/youtube-music-api/pull/3 so I don't need that fork anymore.

It seems that they fixed the Axios version upstream so it should be good now. Cheers!
