### ISSUE TITLE
Can you show how you are doing the auth part here?

### ISSUE THREAD

**Issue by hidimpu** [valeriangalliat/spotify-to-youtube#4]
I'm having so much trouble getting the id print to console, I will be so happy if you can show it live working with code if possible

**Comment by valeriangalliat** [comment]
Hey! The [usage](https://github.com/valeriangalliat/spotify-to-youtube#usage) example still works for me, what error are you getting?

A more practical example (that doesn't assume to already be in an async function context), with more explicit spotify-web-api-node auth options would be:

```js
const SpotifyToYoutube = require('spotify-to-youtube')
const SpotifyWebApi = require('spotify-web-api-node')

const spotifyApi = new SpotifyWebApi({
  clientId: '...',
  clientSecret: '...',
  redirectUri: '...'
})

// Altenratively if you already have an access token.
const spotifyApi = new SpotifyWebApi()
spotifyApi.setAccessToken('...')

async function main() {
  const spotifyToYoutube = SpotifyToYoutube(spotifyApi)
  const id = await spotifyToYoutube('spotify:track:3djNBlI7xOggg7pnsOLaNm')
  console.log(id) // J7_bMdYfSws
}

main()
```

Typically if you don't have an OAuth Spotify app with `clientId`, `clientSecret` and `redirectUri`, you can use the `setAccessToken` method. You can fetch that token by inspecting network requests made by <https://open.spotify.com/>, it's the value of the `Authorization: Bearer` header in `api.spotify.com` requests.

This token is short lived, if you need a more permanent option, you can use the `sp_dc` cookie as in [this other package](https://github.com/valeriangalliat/spotify-buddylist/blob/master/index.js#L3).

Let me know if that helps!

**Comment by hidimpu** [comment]
can we communicate on discord once if you don't mind 
I'm unable to integrate it inside my app 
dimpu#7971 is my discord id

**Comment by valeriangalliat** [comment]
Sure, I added you on Discord :)

**Comment by hidimpu** [comment]
I guess I figured out how to do it  
This worked in my server side
I guess you should update the instructions a bit for more clarity :) 
I guess I haven't received your friend request on discord yet

`
var express = require('express');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

const SpotifyToYoutube = require('spotify-to-youtube');
const SpotifyWebApi = require('spotify-web-api-node');

const spotifyApi = new SpotifyWebApi({
	clientId: '..',
	clientSecret: '...',
	// redirectUri: '...',
});

var app = express();

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

app.get('/', async (req, res) => {
	try {
		// This method authenticates with client id and secret and get the access_token, refresh_token and expires_in

		// This method doesn't actually needs a redirect URL  
		const data = await spotifyApi.clientCredentialsGrant();

		const access_token = data.body['access_token'];
		const refresh_token = data.body['refresh_token'];
		const expires_in = data.body['expires_in'];

		// Then set the access token
		spotifyApi.setAccessToken(access_token);

		const spotifyToYoutube = SpotifyToYoutube(spotifyApi);

		spotifyToYoutube('3djNBlI7xOggg7pnsOLaNm').then((id) => console.log(id));
	} catch (err) {
		console.log(
			'Something went wrong when retrieving an access token',
			err.message
		);
	}

	res.send('Hello World');
});

var listener = app.listen(8080, function () {
	console.log('Listening on port ' + listener.address().port);
});

`

Sorry for bad formatting tho

**Comment by valeriangalliat** [comment]
Awesome! I just updated the readme to make things more clear so I'll close this issue. Cheers =)
